#######################################
#           Monitor config            #
#######################################
monitor=,preferred,auto,1



#######################################
#   		  auto start	          #
#######################################
exec-once = waybar
exec-once = hyprpaper
exec-once = input-remapper-control --command autoload
exec-once = dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP
#exec-once = /usr/lib/polkit-kde-authentication-agent-1

#######################################
#		variables	      #
#######################################
$env = PATH,$HOME/.local/bin:$PATH
$terminal = kitty
$menu = wofi
$mainMod = SUPER
$ctrl = Control_L
$alt = Alt_L
$explorer = thunar
$shift = Shift



#######################################
#		Bindings	      #
#######################################
# learning
# bind = MODIFIERS, KEY, DISPATCHER, ARGUMENT
# bind = SUPER, Q, killactive,
# bind = $mainMod SHIFT, L, workspace, 1
# A dispatcher is basically the action (the thing you want Hyprland to do).
# An argument is the extra information the dispatcher needs to know exactly what to do.


# logout
#---------------------------------------
bind = $mainMod, M, exit
# to move the focus on windows
#---------------------------------------
bindm = $ctrl, mouse:272, 1
# to move the focus on windows
#---------------------------------------
bind = $alt, h, movefocus, left
bind = $alt, l, movefocus, right
bind = $alt, j, movefocus, down
bind = $alt, k, movefocus, up
# for programs
#---------------------------------------
bind = $alt, a, exec, $terminal
bind = $alt, w, killactive
bind = $alt, space, exec, pkill $menu || $menu  # execute this and kill it when pressed again.
bind = $alt, B, exec, firefox
bind = $alt, e, exec, $explorer
# for workspaces 
#--------------------------------------
bind = $alt, 1, workspace, 1
bind = $alt, 2, workspace, 2
bind = $alt, 3, workspace, 3
bind = $alt, 4, workspace, 4
bind = $alt, 5, workspace, 5
bind = $alt $ctrl, l, movetoworkspace, +1
bind = $alt $ctrl, h, movetoworkspace, -1

# bind = MODIFIERS, KEY, DISPATCHER, ARGUMENT

# to switch between them
bind = $alt shift, l, workspace, +1
bind = $alt shift, h, workspace, -1
# Function keys and media
#--------------------------------------
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%-
bind  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_SINK@ toggle # Mute Audio (uses standard 'bind' as a toggle shouldn't repeat)
#-------------------------------------
bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%- 







input {

    kb_layout = us, br
    #kb_variant =
    #kb_model =
    kb_options = grp:win_space_toggle
    #kb_rules =

}






#######################################
#		Appearance	      #
#######################################
general {
    border_size = 3 # int
    gaps_in = 4 # css_gaps
    gaps_out = 8 # css_gaps
    
    resize_on_border = true # lets you resize borders with mouse
    extend_border_grab_area = 15 # int

    locale = us

}

decoration {
    rounding = 20
    rounding_power = 3.0    # [1.0 - 10.0]
    inactive_opacity = 0.5  # [0.0 - 1.0]
    dim_modal = true        # bool
    dim_strength = 0.5      # how much to dim inactive windows [0.0 - 1.0]
    border_part_of_window = true # bool
    
    glow {
        enabled = true  # bool
        range =  10
        color = rgba(ffffffcc)
    }

    blur {
        enabled = true
        size = 3  # blur distance, int
        passes = 3  # int
        # noise = 0.9 # noise to apply. [0.0 - 1.0]
    }

}

animations {
    enabled = true
}
